<?php

declare(strict_types=1);

namespace App\Services\Bess;

use App\Enums\Discipline;
use App\Enums\OwnershipMode;
use App\Enums\PackageType;
use App\Models\PackageInstance;
use App\Models\PackageTemplate;
use App\Models\Project;
use Illuminate\Support\Collection;

class PackageLibraryService
{
    public function __construct(
        private readonly ProjectSetupService $setupService,
    ) {}

    /**
     * Instantiate all applicable package templates into package instances for a project.
     * Evaluates conditional flags and sets default ownership modes.
     */
    public function instantiatePackages(Project $project): Collection
    {
        $templates = PackageTemplate::with(['activityTemplates', 'outputDefinitions', 'dependencyRules'])
            ->orderBy('sort_order')
            ->get();

        $instances = collect();

        foreach ($templates as $template) {
            $applicable = $this->evaluateApplicability($project, $template);
            $ownershipMode = $template->ownership_mode_default;

            // Conditional packages that fail their condition are not applicable
            if ($template->is_conditional && !$applicable) {
                $instance = $this->createInstance($project, $template, $ownershipMode, selected: false, applicable: false);
                $instances->push($instance);
                continue;
            }

            // Topology-driven activities are generated by TopologyActivityGenerator
            // during GraphCompilerService::compile(), not here.
            if ($template->is_topology_driven) {
                continue;
            }

            $instance = $this->createInstance($project, $template, $ownershipMode, selected: true, applicable: true);
            $instances->push($instance);
        }

        return $instances;
    }

    /**
     * Update ownership mode for a package instance. Cascades to included packages.
     */
    public function setOwnershipMode(PackageInstance $instance, OwnershipMode $mode, ?int $includedInPackageId = null): void
    {
        $instance->update([
            'ownership_mode' => $mode,
            'included_in_package_id' => $mode === OwnershipMode::IncludedElsewhere ? $includedInPackageId : null,
        ]);
    }

    /**
     * Toggle package selection (user explicitly selects/deselects optional packages).
     */
    public function toggleSelection(PackageInstance $instance, bool $selected): void
    {
        $instance->update(['selected' => $selected]);
    }

    /**
     * Get all active (selected + applicable) package instances for a project.
     */
    public function getActivePackages(Project $project): Collection
    {
        return PackageInstance::where('project_id', $project->id)
            ->where('selected', true)
            ->where('applicable', true)
            ->with(['template.activityTemplates', 'template.outputDefinitions', 'template.dependencyRules'])
            ->orderBy('id')
            ->get();
    }

    /**
     * Evaluate whether a conditional package is applicable based on project flags.
     */
    private function evaluateApplicability(Project $project, PackageTemplate $template): bool
    {
        if (!$template->is_conditional) {
            return true;
        }

        $flag = $template->condition_flag;
        if ($flag === null) {
            return true;
        }

        $flagValue = $project->getAttribute($flag);

        // For "negative" conditions (hvac_in_vendor_package, fire_in_vendor_package, bess_free_issued),
        // the package is NOT applicable when the flag is TRUE (meaning it's handled elsewhere)
        $negativeFlags = ['hvac_in_vendor_package', 'fire_in_vendor_package', 'bess_free_issued'];

        if (in_array($flag, $negativeFlags, true)) {
            return !$flagValue;
        }

        // For "positive" conditions (switchroom_exists, control_room_exists, etc.),
        // the package IS applicable when the flag is TRUE
        return (bool) $flagValue;
    }

    private function createInstance(
        Project $project,
        PackageTemplate $template,
        OwnershipMode $ownershipMode,
        bool $selected,
        bool $applicable,
        array $extra = [],
    ): PackageInstance {
        // Milestone packages place activities directly under the Milestones
        // branch — no discipline or package sub-nodes.
        $isMilestone = $template->type === PackageType::Milestone;

        // Skip the discipline sub-node when discipline is None to avoid
        // creating an intermediate WBS node literally called "None".
        $disciplineName = ($isMilestone || $template->discipline === Discipline::None)
            ? null
            : $template->discipline->label();

        $wbsNode = $this->setupService->getOrCreateWbsNode(
            $project,
            $template->wbs_category,
            $disciplineName,
            $isMilestone ? null : ($extra['name_override'] ?? $template->name),
            $template->construction_wbs_group,
        );

        return PackageInstance::create(array_merge([
            'project_id' => $project->id,
            'template_id' => $template->id,
            'wbs_node_id' => $wbsNode->id,
            'ownership_mode' => $ownershipMode,
            'selected' => $selected,
            'applicable' => $applicable,
        ], $extra));
    }
}