<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up()
    {
        Schema::create('relationships', function (Blueprint $table) {
            $table->id();
            $table->foreignId('project_id')
                ->constrained('projects')
                ->cascadeOnDelete();

            // ── Relationship Direction ──────────────────────────────────
            $table->foreignId('predecessor_id')
                ->constrained('activity_instances')
                ->cascadeOnDelete();
            $table->foreignId('successor_id')
                ->constrained('activity_instances')
                ->cascadeOnDelete();

            // ── Relationship Type ───────────────────────────────────────
            // FS | SS | FF | SF
            $table->string('relationship_type')->default('FS');
            $table->smallInteger('lag_days')->default(0);    // Positive = lag, negative = lead

            // ── Origin ──────────────────────────────────────────────────
            // internal    = within same package (from activity_templates)
            // dependency  = cross-package via dependency_rules / provider_resolutions
            // interface   = generated by interface_records
            // manual      = user-defined
            $table->string('origin')->default('dependency');

            $table->timestamps();

            // ── Indexes ─────────────────────────────────────────────────
            $table->index('project_id');
            $table->index('predecessor_id');
            $table->index('successor_id');
            $table->unique(['predecessor_id', 'successor_id', 'relationship_type'],
                'unique_relationship');
        });
    }

    public function down()
    {
        Schema::dropIfExists('relationships');
    }
};
